services:
  postgres:
    image: postgres:16-alpine
    container_name: tin_postgres
    environment:
      POSTGRES_USER: tin_user
      POSTGRES_PASSWORD: tin_password
      POSTGRES_DB: tin_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tin_user -d tin_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
