packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': 9.39.2
  '@types/node': ^22.13.14
  '@vitest/coverage-v8': 4.0.16
  better-auth: ^1.2.7
  eslint: 9.39.2
  typescript: 5.9.3
  vitest: 4.0.16

onlyBuiltDependencies:
  - '@prisma/client'
  - prisma
  - msw
